project_id = "ieytagtyadvihuzafvqm"

[functions.generate-content]
verify_jwt = true

[functions.canva-export]
verify_jwt = true

[functions.chatbot]
verify_jwt = false

[functions.chatbot-voice]
verify_jwt = false

[functions.form-ai-helper]
verify_jwt = true

[functions.ai-helper-chat]
verify_jwt = true

[functions.ai-customer-service]
verify_jwt = true

[functions.scrape-social-media]
verify_jwt = true
